import PageShell from '@/components/ui/PageShell'
import PageHeader from '@/components/ui/PageHeader'
import MonoLabel from '@/components/ui/MonoLabel'

export default function TermsPage() {
  return (
    <PageShell back={{ href: '/login', label: 'back' }}>
      <PageHeader kicker="legal" title="Terms" />
      <article className="px-5 pb-12 space-y-6" style={{ fontFamily: 'var(--font-serif)', fontSize: '15px', lineHeight: 1.6 }}>

        <section>
          <MonoLabel className="block mb-2">what this is</MonoLabel>
          <p>Bunnyhop is a personal trip-planning tool for families and small groups. It is not a commercial travel service, booking platform, or travel agency. We do not sell travel products, process payments for travel, or guarantee any booking or recommendation.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">your account</MonoLabel>
          <p>You sign in with your Google account. You are responsible for keeping your account secure. Trip creation may require admin approval. You can participate in trips you are invited to regardless of approval status.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">your content</MonoLabel>
          <p>You own the data you add to Bunnyhop — trip details, bookings, notes, votes. By using the app, you grant us permission to store, process, and display your content to other trip participants as part of the service. You also grant permission to send your content to the AI services described in the Privacy Policy for feature functionality.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">ai-generated content</MonoLabel>
          <p>Recommendation cards, trip cover images, and parsed booking data are generated by AI models (Claude by Anthropic, Gemini by Google). This content is provided as-is with no guarantee of accuracy, completeness, or suitability. Always verify recommendations, prices, hours, and ratings independently before making travel decisions.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">invite codes</MonoLabel>
          <p>Each trip has an invite code that acts as a bearer secret. Anyone with the code can view the trip, join as a participant, and post booking data via the agent API. Share invite codes only with people and AI agents you trust. The site admin is not responsible for unauthorized access resulting from shared invite codes.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">acceptable use</MonoLabel>
          <p>Use Bunnyhop for its intended purpose: collaborative trip planning. Do not use it to: spam other users, submit false or malicious data, attempt to access trips you are not invited to, or abuse the AI generation endpoints.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">service availability</MonoLabel>
          <p>Bunnyhop is provided as-is, with no uptime guarantees. The service depends on third-party infrastructure (Supabase, Vercel, Anthropic, Google) and may be unavailable if any of these services experience issues. We do not guarantee that your data will be preserved indefinitely — maintain your own records of important bookings.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">limitation of liability</MonoLabel>
          <p>To the fullest extent permitted by law, Bunnyhop and its creators are not liable for any damages arising from your use of the service, including but not limited to: missed bookings, incorrect recommendations, data loss, or unauthorized access via shared invite codes.</p>
        </section>

        <section>
          <MonoLabel className="block mb-2">changes</MonoLabel>
          <p>These terms may be updated as the service evolves. Continued use of the app after changes constitutes acceptance of the updated terms.</p>
        </section>

        <p className="detail-mono" style={{ opacity: 0.5 }}>Last updated: April 2026</p>
      </article>
    </PageShell>
  )
}
