-- Trip cover images: a single editorial-style photograph per trip,
-- generated by Gemini Imagen on trip creation. Stored in Supabase
-- Storage under the public 'trip-covers' bucket. Only rendered in
-- the editorial UI tree (the default UI doesn't show covers).

alter table trips
  add column if not exists cover_image_url text;

-- Public-read storage bucket. Service role writes images on demand
-- via the /api/trips/[tripId]/generate-cover route; everyone with
-- the URL can read them via <img src>.
insert into storage.buckets (id, name, public)
values ('trip-covers', 'trip-covers', true)
on conflict (id) do nothing;
